#!/bin/sh
smartctl -i /dev/$1 > SMART.log

smartctl -H /dev/$1 >> SMART.log
if [ $? != 0 ];then 
  echo "Show SMART health failed: $1" >> SMART.log
fi

while [ 1 ];do
sleep 300
smartctl -a /dev/$1
if [ $? != 0 ];then 
  echo "SMART Drive failed Predicted: $1" >> SMART.log
  smartctl -a /dev/$1 >> SMART.log
fi

smartctl -a /dev/$1 | egrep "(Reallocated_Sector_Ct|Raw_Read_Error_Rate|Seek_Error_Rate|Current_Pending_Sector)" | egrep -v 'Always       -       0'
if [ $? == 0 ];then
  echo "Reallocated_Sector_Ct or Raw_Read or Seek Error_Rate or Current_Pending_Sector failed: $1" >> SMART.log
  smartctl -a /dev/$1 >> SMART.log
fi

smartctl -H /dev/$1 
if [ $? != 0 ];then 
  echo "Show SMART health failed: $1" >> SMART.log
  smartctl -H /dev/$1  >> SMART.log
fi

smartctl -q errorsonly -l selftest /dev/$1
if [ $? != 0 ];then 
  echo "Drive selftest failed: $1" >> SMART.log
  smartctl -q errorsonly -l selftest /dev/$1  >> SMART.log
fi

done
